### PR TITLE
Fix for iPad in iPhone mode

### PR DESCRIPTION
**Pull request by krusek**
This fixes empty thumbnails for iPad when in iPhone mode. It is a weird edge case, but it fixes it nonetheless.

### CODE REVIEW

**Comment by krusek** [comment]
fixes #217

**Comment by krusek** [comment]
simulator screen shot apr 7 2016 12 46 28 pm

**Comment by chiunam** [comment]
@krusek I am very busy on my personal matter so I have no time to verify your fix. This PR will be merged as pre-release for those need this urgent fix.

**Comment by jiaowochunge** [comment]
swift can not apply this pre release version. the important method is in 'PHImageManager+CTAssetsPickerController.h' , but this file is not public.
2237fe76-0e16-422f-b4bc-a1cb66f6da4f

**Pull request merged**
