### PR TITLE
Dutch translation fixes

### PR DESCRIPTION
**Pull request by Remyoman**
Added AppCode related files to the gitignore file.
Fixed an issue in the Dutch translation that resulted in an underflow.

### CODE REVIEW

**Comment by chiunam** [comment]
@Remyoman Thanks. I have manually merged the translations fix.

**Comment by Remyoman** [comment]
No problem, thank you for the fast handling.

One question: Why not add the appCode related gitignore lines?

**Comment by chiunam** [comment]
@Remyoman I managed to put your PR in [v3.1.0](https://github.com/chiunam/CTAssetsPickerController/releases/tag/v3.1.0) update and not quite sure about what appCode actually is. I would be grateful if you could direct me more about it. Thanks.

**Comment by Remyoman** [comment]
AppCode is an Xcode compatible environment which can be used to develop iOS apps. It makes use of the Xcode command line tools and other internal Xcode features to make it work.

It is part of the Jetbrains IDE's which are all based on the same core which is open source if I recall correctly. You can find more information on their website. https://www.jetbrains.com/objc/

I will leave it at this before I go on a rant, I hope this satisfies your request.

**Comment by chiunam** [comment]
@Remyoman thanks for your supplements, will merge it in next update. Thanks.

**Pull request closed without merging**
