### PR TITLE
Translate "Cannot Play Stream Video" into Japanese

### PR DESCRIPTION
**Pull request by tomoyuki28jp**
Is this all we need to translate into Japanese?
I assume "Stream Video" is just a normal video.

### CODE REVIEW

**Comment by chiunam** [comment]
@tomoyuki28jp Thanks. "Stream Video" is video stored in iCloud.

**Comment by chiunam** [comment]
BTW, you might like to translate the "OK" message too.

**Comment by tomoyuki28jp** [comment]
@chiunam Thanks for your explanation. I just made another pull request: https://github.com/chiunam/CTAssetsPickerController/pull/123

**Comment by tomoyuki28jp** [comment]
And I think we don't need to translate the "OK" message :)

**Pull request merged**
